-- =============================================
-- SUPABASE SCHEMA FOR ABHIMANYU RAJ PORTFOLIO
-- =============================================
-- Run this SQL in Supabase SQL Editor (Dashboard -> SQL Editor -> New Query)

-- =============================================
-- 1. CREATE BLOGS TABLE (ADVANCED)
-- =============================================
create table if not exists public.blogs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  title text not null,
  slug text not null unique,
  excerpt text,
  content text not null,
  cover_image text,
  category text,
  tags text[],
  reading_time integer default 5,
  featured boolean default false,
  published boolean default false
);

-- =============================================
-- 2. CREATE REVIEWS/TESTIMONIALS TABLE
-- =============================================
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text,
  designation text,
  company text,
  message text not null,
  rating smallint default 5 check (rating >= 1 and rating <= 5),
  approved boolean default false,
  image text
);

-- =============================================
-- 3. CREATE CONTACT MESSAGES TABLE (NEW)
-- =============================================
create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  mobile text,
  service text,
  budget text,
  message text not null,
  is_read boolean default false
);

-- =============================================
-- 4. ENABLE ROW LEVEL SECURITY (RLS)
-- =============================================
alter table public.blogs enable row level security;
alter table public.reviews enable row level security;
alter table public.contact_messages enable row level security;

-- =============================================
-- 5. CREATE POLICIES
-- =============================================

-- BLOGS POLICIES
-- Allow public read access to published blogs
create policy "Public blogs are viewable by everyone" 
  on public.blogs for select 
  using (published = true);

-- Allow authenticated (admin) users full access to blogs
create policy "Admins can manage blogs" 
  on public.blogs for all 
  using (auth.role() = 'authenticated');

-- REVIEWS POLICIES
-- Allow public read access to approved reviews
create policy "Public reviews are viewable by everyone" 
  on public.reviews for select 
  using (approved = true);

-- Allow authenticated (admin) users full access to reviews
create policy "Admins can manage reviews" 
  on public.reviews for all 
  using (auth.role() = 'authenticated');

-- Allow anyone to insert a review (for submission form)
create policy "Anyone can submit a review" 
  on public.reviews for insert 
  with check (true);

-- CONTACT MESSAGES POLICIES
-- Allow anyone to insert a contact message
create policy "Anyone can submit contact message" 
  on public.contact_messages for insert 
  with check (true);

-- Allow authenticated (admin) users full access to contact messages
create policy "Admins can manage contact messages" 
  on public.contact_messages for all 
  using (auth.role() = 'authenticated');

-- =============================================
-- 6. CREATE ADMIN USER (Run in Supabase Dashboard)
-- =============================================
-- NOTE: Admin user creation must be done via Supabase Dashboard:
-- 
-- Option 1: Dashboard UI
--   1. Go to Authentication -> Users
--   2. Click "Add user" -> "Create new user"
--   3. Email: abhimanyuraj134@gmail.com
--   4. Password: @Abhi8252
--   5. Check "Auto Confirm User"
--
-- Option 2: SQL (if you have admin rights)
-- This creates the user but you may need to confirm via dashboard
-- INSERT INTO auth.users (email, encrypted_password, email_confirmed_at, role)
-- VALUES ('abhimanyuraj134@gmail.com', crypt('@Abhi8252', gen_salt('bf')), now(), 'authenticated');

-- =============================================
-- DONE! Your schema is ready.
-- =============================================

